server: 
  port: 9004
spring: 
  application:  
    name: cquptCommunity-article #指定服务名

  #配置springDataJPA
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.132:3306/cquptCommunity_article?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

  #配置springDateMongoDB
  data:
    mongodb:
      host: 192.168.174.132
      database: recruitdb  #要连接的数据库

  #配置springDataRedis
  redis:
    host: 192.168.174.132

#把自己注册到eureka中（url是eureka注册中心的访问路径）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka   #eureka注册中心的访问路径
  instance:
    prefer-ip-address: true #实现跨域访问