server:
  port: 9010
spring:
  application:
    name: cquptCommunity-friend  #注册到eureka注册中心中的名称

  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.132:3306/cquptCommunity_friend?characterEncoding=utf-8
    username: root
    password: root

  #配置jpa
  jpa:
    database: mysql  #数据库类型
    show-sql: true   #显示sql

  #配置redis
  redis:
    host: 192.168.174.132

#配置要使用的JWT的配置信息：凡是涉及登录的都需要使用到
jwt:
  config:
    key: cquptCommunity   #所加的盐

#把自己注册到eureka中（url是eureka注册中心的访问路径）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka   #eureka注册中心的访问路径
  instance:
    prefer-ip-address: true #实现跨域访问

#如果使用的是feign组件的熔断器，需要手动开启
feign:
  hystrix:
    enabled: true