server: 
  port: 9008
spring: 
  application:  
    name: cquptCommunity-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.132:3306/cquptCommunity_user?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

  #配置redis
  redis:
    host: 192.168.174.132

  #配置rabbitmq
  rabbitmq:
    host: 192.168.174.132   #指定要连接的主机