server: 
  port: 9009
spring:
  application:
    name: cquptCommunity_sms  #微服务的名称

  #配置rabbitmq
  rabbitmq:
    host: 192.168.174.132   #指定要连接的主机

#把自己注册到eureka中（url是eureka注册中心的访问路径）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka   #eureka注册中心的访问路径
  instance:
    prefer-ip-address: true #实现跨域访问